<?php

namespace Service\Users;

class Controller_State_Admin_List extends Controller_State_Admin
{
    public function actionPrepare()
    {

        //актививация выбранного пункта меню
        if ($this instanceof Controller_State_Admin_List_Admins) {
            if (isset($this->_application->menu['users']['menu']['admins'])) {
                $this->_application->menu['users']['menu']['admins']['active'] = true;
            }
        }
        else if ($this instanceof Controller_State_Admin_List_Bad) {
            if (isset($this->_application->menu['users']['menu']['bad'])) {
                $this->_application->menu['users']['menu']['bad']['active'] = true;
            }
        }
        else {
            if (isset($this->_application->menu['users']['menu']['all'])) {
                $this->_application->menu['users']['menu']['all']['active'] = true;
            }
        }


        $userId = $this->_request->get['userId']->int(0);

        if ($userId > 0) {
            $user = $this->factoryUsers->users->getById($userId);

            if ($user !== null) {
                $this->_application->setUserToCookie($user);

                return $this->_response->setLocation('/');
            }
        }


        //Проверка качества аккаунта пользователя (запуск из админки)
        $check = $this->_request->get['check']->int(0);
        if ($check > 0) {
            $user = $this->factoryUsers->users->getById($check, true);

            if ($user !== null) {
                $this->_application->User = $user;
                $this->_application->UserID = $user->userId;
                $this->_application->updateUserFromVK();

                return $this->_response->setLocation($this->_request->server['REDIRECT_URL']->string());
            }
        }

        //Удаление пользователя (запуск из админки)
        $delUserId = $this->_request->get['del']->int(0);
        if ($delUserId > 0) {
            $user = $this->factoryUsers->users->getById($delUserId);

            if ($user === null | $user->userId != $delUserId) {
                return $this->_response->setStatus(\System\HttpResponse::S4_NOT_FOUND);
            }

            $this->factoryUsers->users->delete($user->userId);

            return $this->_response->setLocation($this->_request->server['REDIRECT_URL']->string());
        }



        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {

        $this->_application->page = 'admin-users';
        $page = $this->_params['page'];
        $query = $this->factoryUsers->users->query()->limit($this->_limit)->offset(($page - 1) * $this->_limit)->sort('userId',
            'DESC')->sqlCalcFoundRows(true);

        $q = $this->_request->get['q']->string('');
        $url = '/admin/users/list/@p@?q=' . urlencode($q);
        $title = 'Пользователи';


        if ($this instanceof Controller_State_Admin_List_Online) {
            $title = 'Пользователи онлайн';
            $url = '/admin/users/list/online/@p@?q=' . urlencode($q);
            $time = time() - (10 * 60);
            $query->filter->fieldValue('lastLogin', '>', $time);
        }

        if ($this instanceof Controller_State_Admin_List_Ban) {
            $url = '/admin/users/list/ban/@p@?q=' . urlencode($q);
            $title = 'Забаненные пользователи';
            $query->filter->fieldValue('ban', '=', true);
        }

        if ($this instanceof Controller_State_Admin_List_Bad) {
            $url = '/admin/users/list/bad/@p@?q=' . urlencode($q);
            $title = 'Не прошли проверку качества';
            $query->filter->fieldValue('bad', '>', 0);
        }

        if ($this instanceof Controller_State_Admin_List_AccessToken) {
            $url = '/admin/users/list/access_token/@p@?q=' . urlencode($q);
            $title = 'Пользователи с токенами';
            $query->filter->fieldValue('access_token', '!=', '');
        }

        if ($this instanceof Controller_State_Admin_List_TokenRequire) {
            $url = '/admin/users/list/token_require/@p@?q=' . urlencode($q);
            $title = 'token_require';
            $query->filter->fieldValue('token_require', '=', true);
        }

        if ($this instanceof Controller_State_Admin_List_Admins) {
            $url = '/admin/users/list/admins/@p@?q=' . urlencode($q);
            $title = 'Администраторы';
            $query->filter->fieldValue('userType', '=', \Service\Users\Model_Config::TYPE_ADMIN);
        }

        if ($q) {
            if ($q === strval(intval($q))) {
                $query->filter->fieldValue('userId', '=', intval($q));
            } else {
                $query->filter->aggregatorOpen('OR')
                    ->fieldValue('userId', '=', intval($q))
                    ->fieldValue('name', 'LIKE', '%' . $q . '%')
                    ->fieldValue('email', 'LIKE', '%' . $q . '%')
                    ->fieldValue('login', 'LIKE', '%' . $q . '%')
                    ->aggregatorClose();
            }
        }

        $it = $query->iterator();

        $pageslink = \Lib_Html::GetNavigationPagesNumber(
            $this->_limit,
            4,
            $it->getTotal(),
            $page,
            $url,
            1
        );

        $list = [];
        $userIds = [];

        foreach ($it as $user) {
            $userIds[] = $user->userId;
            $list[] = $user;
        }

        $orders = [];

        if (count($userIds)) {
            $query = $this->factoryOrders->orders->query();
            $query->filter->fieldCollection('userId', 'IN', $userIds);
            $it = $query->iterator();

            foreach ($it as $order) {
                if (!isset($orders[$order->userId])) {
                    $orders[$order->userId] = 0;
                }
                $orders[$order->userId]++;
            }
        }

        //pd($list);

        $vars = [
            'title' => $title,
            'list' => $list,
            'orders' => $orders,
            'pageslink' => $pageslink,
            'errors' => $this->_errors,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/list', $vars));
    }

    public function actionPost()
    {
        $action = $this->_request->post['action']->string();
        $service = '';
        $title = '';

        switch ($action) {
            case 'addBalance':
                return $this->_addBalance();
            case 'addKarma':
                return $this->_addKarma();
            case 'getUserDetail':
                return $this->_getUserDetail();
            case 'saveUserType':
                return $this->_saveUserType();
            case 'getPacks':
                return $this->_getPacks();
            case 'getAuto':
                if (!$service) {
                    $service = 'auto';
                }

                if (!$title) {
                    $title = 'Автоведение';
                }
            // no break
            case 'getPosting':
                if (!$service) {
                    $service = 'posting';
                }

                if (!$title) {
                    $title = 'Автопостинг';
                }
            // no break
            case 'getGrabber':
                if (!$service) {
                    $service = 'grabber';
                }

                if (!$title) {
                    $title = 'Граббер';
                }
            // no break
            case 'getSpecial':
                if (!$service) {
                    $service = 'special';
                }

                if (!$title) {
                    $title = 'Спецзадания';
                }
            // no break
            case 'getBot':
                if (!$service) {
                    $service = 'bot';
                }

                if (!$title) {
                    $title = 'Автобот';
                }

                return $this->_getServiceForm($service, $title);
            case 'activateService':
                return $this->_activateService();
            case 'referrerToggle':
                return $this->_referrerToggle();
            case 'packActivate':
                return $this->_packActivate();
        }

        return $this->_response->setStatus(\System\HttpResponse::S4_BAD_REQUEST);
    }

    private function _addBalance()
    {
        $user = $this->factoryUsers->users->getById($this->_request->post['userId']->int(), true);

        if ($user === null) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Не могу найти пользователя']);
        }

        $sum = $this->_request->post['sum']->dec();

        if (!$sum) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Укажите сумму']);
        }

        $balance = $this->factoryUsers->users->balance->getNew();
        $balance->userId = $user->userId;
        $balance->balance = $sum;
        $balance->balanceFrom = $user->balance;

        $user->balance += $sum;

        if ($this->factoryUsers->users->save($user)) {
            $balance->balanceTo = $user->balance;
            $balance->dateCreate = time();
            $balance->comment = 'Корректировка модератором';
            $this->factoryUsers->users->balance->save($balance);
            $message = $this->factoryMessages->users->getNew();
            $message->userId = $user->userId;
            $message->type = \Service\Messages\Model_Config::TYPE_SYSTEM;
            $message->isDone = false;
            $message->text = 'Баланс скорректирован администратором';
            $this->factoryMessages->users->save($message);

            return $this->_response->setJson([
                'success' => true,
                'userId' => $user->userId,
                'balanceText' => number_format($user->balance, 1, '.', ' '),
            ]);
        }
    }

    private function _addKarma()
    {
        $user = $this->factoryUsers->users->getById($this->_request->post['userId']->int(), true);

        if ($user === null) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Не могу найти пользователя']);
        }

        $sum = $this->_request->post['sum']->dec();

        if (!$sum) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Укажите сумму']);
        }

        $karma = $this->factoryUsers->users->karma->getNew();
        $karma->userId = $user->userId;
        $karma->dateCreate = time();
        $karma->karma = $sum;
        $karma->karmaFrom = $user->karma;
        $user->karma += $sum;
        $karma->karmaTo = $user->karma;
        $karma->comment = 'Корректировка кармы модератором';

        if ($this->factoryUsers->users->save($user)) {
            $this->factoryUsers->users->karma->save($karma);
            $message = $this->factoryMessages->users->getNew();
            $message->userId = $this->_application->UserID;
            $message->type = \Service\Messages\Model_Config::TYPE_SYSTEM;
            $message->isDone = false;
            $message->text = 'Карма скорректирована администратором';
            $this->factoryMessages->users->save($message);

            return $this->_response->setJson(['success' => true, 'userId' => $user->userId, 'karma' => $user->karma]);
        }
    }

    private function _saveUserType() {
        $userId = $this->_request->post['userId']->int(0);

        if (!$userId) {
            return $this->_response->setStatus(\System\HttpResponse::S4_NOT_FOUND);
        }
        $user = $this->factoryUsers->users->getById($userId);

        if ($user === null) {
            return $this->_response->setStatus(\System\HttpResponse::S4_NOT_FOUND);
        }

        $user->makeShadow();
        $user->userType = $this->_request->post['userType']->int(\Service\Users\Model_Config::TYPE_USER);
        $this->factoryUsers->users->save($user);

        return $this->_response->setJson(['success' => true]);
    }

    private function _getUserDetail()
    {
        $userId = $this->_request->post['userId']->int(0);

        if (!$userId) {
            return $this->_response->setStatus(\System\HttpResponse::S4_NOT_FOUND);
        }
        $user = $this->factoryUsers->users->getById($userId);

        if ($user === null) {
            return $this->_response->setStatus(\System\HttpResponse::S4_NOT_FOUND);
        }

        $autoGroups = $this->factoryAuto->auto->groups->getByUserId($user->userId);
        $grabberGroups = $this->factoryGrabber->groups->getByUserId($user->userId);
        $postingGroups = $this->factoryPosting->groups->getByUserId($user->userId);
        $specialGroups = $this->factoryTasks->specialGroups->getByUserId($user->userId);

        $query = $this->factoryOrders->orders->packs->query()->limit(100)->sort('price', 'ASC');
        $it = $query->iterator();
        $packs = [];

        foreach ($it as $pack) {
            $packs[$pack->packId] = $pack;
        }

        $orders = $this->factoryOrders->orders->getByUserId($userId);

        //провелим токен пользователя на валидность
        $response = $this->VK->checkUserAccessToken($user->access_token);
        if (!empty($response['error'])) $valid_access_token = $response['errorText'];
        else $valid_access_token = 'Токен валидный';

        $html = \STPL::Fetch('admin/users/detail', [
            'user' => $user,
            'autoGroups' => $autoGroups,
            'grabberGroups' => $grabberGroups,
            'postingGroups' => $postingGroups,
            'specialGroups' => $specialGroups,
            'packs' => $packs,
            'orders' => $orders,
            'valid_access_token' => $valid_access_token
        ]);

        return $this->_response->setJson(['success' => true, 'html' => $html]);
    }

    private function _getPacks()
    {
        $userId = $this->_request->post['userId']->int(0);
        $user = $this->factoryUsers->users->getById($userId, true);

        if ($user === null) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Не удалось получить пользователя']);
        }

        $query = $this->factoryOrders->orders->packs->query()->limit(100)->sort('price', 'ASC');
        $it = $query->iterator();
        $list = [];

        foreach ($it as $pack) {
            $list[] = $pack;
        }

        $query = $this->factoryOrders->orders->query()->limit(1);
        $query->filter->fieldValue('userId', '=', $user->userId)
            ->fieldValue('packId', '>', 0);
        $it = $query->iterator();
        $orders = [];

        foreach ($it as $order) {
            $orders[] = $order;
        }
        $first = false;
        $bonus = 0;

        if (!count($orders)) {
            $first = true;
            $bonusSettings = \Service\Users\Model_Config::GetBonusSettings();
            $bonus = $bonusSettings['buy'];
        }

        $vars = [
            'list' => $list,
            'first' => $first,
            'bonus' => $bonus,
            'userId' => $user->userId,
        ];

        return $this->_response->setJson(['success' => true, 'html' => \STPL::Fetch('admin/users/packs', $vars)]);
    }

    private function _getServiceForm($service, $title)
    {
        $userId = $this->_request->post['userId']->int(0);
        $user = $this->factoryUsers->users->getById($userId, true);

        if ($user === null) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Не удалось получить пользователя']);
        }

        $vars = [
            'userId' => $user->userId,
            'service' => $service,
            'title' => $title,
            'settings' => json_decode(file_get_contents(\Service\Orders\Model_Config::$settings), true),
        ];

        return $this->_response->setJson(['success' => true, 'html' => \STPL::Fetch('admin/users/service', $vars)]);
    }

    private function _activateService()
    {
        $service = $this->_request->post['service']->string();
        $userId = $this->_request->post['userId']->int(0);
        $user = $this->factoryUsers->users->getById($userId);
        $month = $this->_request->post['month']->int(0);

        $settings = json_decode(file_get_contents(\Service\Orders\Model_Config::$settings), true);

        if ($service == 'auto') {
            $auto = $this->factoryAuto->auto->getByUserId($user->userId, true);

            if ($auto === null) {
                $auto = $this->factoryAuto->auto->getNew();
                $auto->userId = $user->userId;
                $auto->dateCreate = time();
            }
            $auto->isActive = true;
            $auto->dateValid += strtotime('+' . intval($settings[$service]['months'][$month]) . ' MONTH');
            $slots = $auto->getSlots();
            $slots[] = intval($settings[$service]['months'][$month]);
            $auto->setSlots($slots);
            $this->factoryAuto->auto->save($auto);
        } elseif ($service == 'posting') {
            $posting = $this->factoryPosting->postings->getByUserId($user->userId, true);

            if ($posting === null) {
                $posting = $this->factoryPosting->postings->getNew();
                $posting->userId = $user->userId;
                $posting->dateCreate = time();
            }
            $posting->isActive = true;
            $posting->dateValid += strtotime('+' . intval($settings[$service]['months'][$month]) . ' MONTH');
            $slots = $posting->getSlots();
            $slots[] = intval($settings[$service]['months'][$month]);
            $posting->setSlots($slots);
            $this->factoryPosting->postings->save($posting);
        } elseif ($service == 'grabber') {
            $grabber = $this->factoryGrabber->grabbers->getByUserId($user->userId, true);

            if ($grabber === null) {
                $grabber = $this->factoryGrabber->grabbers->getNew();
                $grabber->userId = $user->userId;
                $grabber->dateCreate = time();
            }
            $grabber->isActive = true;
            $grabber->dateValid += strtotime('+' . intval($settings[$service]['months'][$month]) . ' MONTH');
            $slots = $grabber->getSlots();
            $slots[] = intval($settings[$service]['months'][$month]);
            $grabber->setSlots($slots);
            $this->factoryGrabber->grabbers->save($grabber);
        } elseif ($service == 'special') {
            $special = $this->factoryTasks->specials->getByUserId($user->userId, true);

            if ($special === null) {
                $special = $this->factoryTasks->specials->getNew();
                $special->userId = $user->userId;
                $special->dateCreate = time();
            }
            $special->isActive = true;
            $special->dateValid += strtotime('+' . intval($settings[$service]['months'][$month]) . ' MONTH');
            $slots = $special->getSlots();
            $slots[] = intval($settings[$service]['months'][$month]);
            $special->setSlots($slots);
            $this->factoryTasks->specials->save($special);
        } elseif ($service == 'bot') {
            $bot = $this->factoryBot->bots->getByUserId($user->userId, true);

            if ($bot === null) {
                $bot = $this->factoryBot->bots->getNew();
                $bot->userId = $user->userId;
                $bot->dateCreate = time();
                $bot->isBot = array_sum(\Service\Bot\Model_Config::$botTypes);
            }
            $bot->isActive = true;
            $bot->isPro = true;
            $bot->dateValid = max($bot->dateCreate, $bot->dateValid);
            $bot->dateValid = strtotime('+' . intval($settings[$service]['months'][$month]) . ' MONTH',
                $bot->dateValid);
            $this->factoryBot->bots->save($bot);
        }

        return $this->_response->setJson(['success' => true, 'userId' => $user->userId]);
    }

    private function _referrerToggle()
    {
        $userId = $this->_request->post['userId']->int(0);
        $user = $this->factoryUsers->users->getById($userId, true);

        $user->isRefferer = !$user->isRefferer;
        $this->factoryUsers->users->save($user);

        return $this->_response->setJson(['success' => true]);
    }

    private function _packActivate()
    {
        $packId = $this->_request->post['packId']->int(0);
        $userId = $this->_request->post['userId']->int(0);

        $gift = $this->factoryOrders->gifts->getNew();
        $gift->adminId = $this->_application->UserID;
        $gift->userId = $userId;
        $gift->packId = $packId;
        $gift->dateCreate = time();
        $gift->dateValid = strtotime('+1 MONTH');
        $gift->isActive = false;
        $gift->isActiveDate = null;

        if ($this->factoryOrders->gifts->save($gift)) {
            return $this->_response->setJson(['success' => true, 'userId' => $userId]);
        }
    }
}
