<?php

namespace Service\Users;

class Controller_State_Admin_Referrers extends Controller_State_Admin
{
    public function actionPrepare()
    {
        if (isset($this->_application->menu['users']['menu']['referrers'])) {
            $this->_application->menu['users']['menu']['referrers']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        $this->_application->page = 'admin-users';
        $page = $this->_request->get['p']->int(0);
        $query = $this->factoryUsers->users->query()->limit($this->_limit)->offset(($page - 1) * $this->_limit)->sort('userId',
            'DESC')->sqlCalcFoundRows(true);
        $query->filter->fieldValue('parentId', '>', 0);

        $it = $query->iterator();

        $pageslink = \Lib_Html::GetNavigationPagesNumber(
            $this->_limit,
            4,
            $it->getTotal(),
            $page,
            '/admin/users/referrers?p=@p@',
            1
        );

        $list = [];

        foreach ($it as $user) {
            $list[] = $user;
        }

        $vars = [
            'list' => $list,
            'pageslink' => $pageslink,
            'errors' => $this->_errors,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/referrers', $vars));
    }

    public function actionPost()
    {
    }
}
