<?php

namespace Service\Tasks;

/**
 * Class Controller_State_Admin_Blacklist
 *
 * @package Service\Tasks
 */
class Controller_State_Admin_Blacklist extends Controller_State_Admin
{
    public function actionPrepare()
    {
        if (isset($this->_application->menu['tasks']['menu']['black'])) {
            $this->_application->menu['tasks']['menu']['black']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        if (isset($this->_application->menu['black'])) {
            $this->_application->menu['black']['active'] = true;
        }
        $data = file_get_contents(ENGINE_PATH . 'static/black.txt');
        $vars = [
            'data' => $data,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/blacklist', $vars));
    }

    public function actionPost()
    {
        $data = $this->_request->post['data']->string();
        file_put_contents(ENGINE_PATH . 'static/black.txt', $data);

        return null;
    }
}
