<?php

namespace Service\Tasks;

class Controller_State_Admin_Countries extends Controller_State_Admin
{
    public function actionPrepare()
    {
        if (isset($this->_application->menu['tasks']['menu']['cities'])) {
            $this->_application->menu['tasks']['menu']['cities']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        if ($this->_request->get['toggle']->int(0)) {
            $city = $this->factoryUsers->countries->getById($this->_request->get['toggle']->int(0), true);

            if ($city) {
                $city->isVisible = !$city->isVisible;
                $this->factoryUsers->countries->save($city);
            }

            return $this->_response->setLocation($this->_request->server['DOCUMENT_URI']->string() . '?p=' . $this->_request->get['p']->int(1));
        }
        $page = $this->_request->get['p']->int(1);
        $query = $this->factoryUsers->countries->query()->limit($this->_limit)->offset($this->_limit * ($page - 1))->sort('count',
            'DESC')->sqlCalcFoundRows(true);
        $it = $query->iterator();

        $pageslink = \Lib_Html::GetNavigationPagesNumber(
            $this->_limit,
            4,
            $it->getTotal(),
            $page,
            '/admin/tasks/cities?p=@p@',
            1
        );

        $vars = [
            'page' => $page,
            'list' => $it,
            'pageslink' => $pageslink,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/countries', $vars));
    }

    public function actionPost()
    {
        // TODO: Implement actionPost() method.
    }
}
