<?php

namespace Service\Tasks;

/**
 * Class Controller_State_Amin
 *
 * @package Service\Tasks
 */
class Controller_State_Admin_Prices extends Controller_State_Admin
{
    public function actionPrepare()
    {
        if (isset($this->_application->menu['tasks']['menu']['prices'])) {
            $this->_application->menu['tasks']['menu']['prices']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        if (isset($this->_application->menu['tasks-prices'])) {
            $this->_application->menu['tasks-prices']['active'] = true;
        }
        $this->_application->getSettings();
        $appSettings = $this->_application->getSettings();
        $settings = [
            'price_likes_buy' => '',
            'price_likes_sell' => '',
            'price_likes_sell_negative' => '',
            'price_likes_sell_positive' => '',

            'price_reposts_buy' => '',
            'price_reposts_sell' => '',
            'price_reposts_sell_negative' => '',
            'price_reposts_sell_positive' => '',

            'price_comments_buy' => '',
            'price_comments_sell' => '',
            'price_comments_sell_negative' => '',
            'price_comments_sell_positive' => '',

            'price_join_buy' => '',
            'price_join_sell' => '',
            'price_join_sell_negative' => '',
            'price_join_sell_positive' => '',

            'price_friends_buy' => '',
            'price_friends_sell' => '',
            'price_friends_sell_negative' => '',
            'price_friends_sell_positive' => '',

            'price_polls_buy' => '',
            'price_polls_sell' => '',
            'price_polls_sell_negative' => '',
            'price_polls_sell_positive' => '',

            'price_views_buy' => '',
            'price_views_sell' => '',
            'price_views_sell_negative' => '',
            'price_views_sell_positive' => '',

            'price_video_buy' => '',
            'price_video_sell' => '',
            'price_video_sell_negative' => '',
            'price_video_sell_positive' => '',

            'percent_sex' => '',
            'percent_ageFrom' => '',
            'percent_ageTo' => '',
            'percent_country' => '',
            'percent_city' => '',
            'percent_relation' => '',
            'percent_avatarCount' => '',
            'percent_filled' => '',
            'percent_pageAge' => '',
            'percent_followersCount' => '',
            'percent_interestingPage' => '',
            'percent_frequencyPost' => '',
        ];

        $percents = json_decode(file_get_contents(ENGINE_PATH . 'engine/Service/Tasks/Model/Config.json'), true);

        if (!is_array($percents)) {
            $percents = [];
        }

        foreach ($appSettings as $name => $val) {
            $settings[$name] = $val;
        }
        $vars = [
            'settings' => $settings,
            'percents' => $percents,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/prices', $vars));
    }

    public function actionPost()
    {
        $settings = [
            'price_likes_buy' => '',
            'price_likes_sell' => '',
            'price_likes_sell_negative' => '',
            'price_likes_sell_positive' => '',

            'price_reposts_buy' => '',
            'price_reposts_sell' => '',
            'price_reposts_sell_negative' => '',
            'price_reposts_sell_positive' => '',

            'price_comments_buy' => '',
            'price_comments_sell' => '',
            'price_comments_sell_negative' => '',
            'price_comments_sell_positive' => '',

            'price_join_buy' => '',
            'price_join_sell' => '',
            'price_join_sell_negative' => '',
            'price_join_sell_positive' => '',

            'price_friends_buy' => '',
            'price_friends_sell' => '',
            'price_friends_sell_negative' => '',
            'price_friends_sell_positive' => '',

            'price_polls_buy' => '',
            'price_polls_sell' => '',
            'price_polls_sell_negative' => '',
            'price_polls_sell_positive' => '',

            'price_views_buy' => '',
            'price_views_sell' => '',
            'price_views_sell_negative' => '',
            'price_views_sell_positive' => '',

            'price_video_buy' => '',
            'price_video_sell' => '',
            'price_video_sell_negative' => '',
            'price_video_sell_positive' => '',

            'percent_sex' => '',
            'percent_ageFrom' => '',
            'percent_ageTo' => '',
            'percent_country' => '',
            'percent_city' => '',
            'percent_relation' => '',
            'percent_avatarCount' => '',
            'percent_filled' => '',
            'percent_pageAge' => '',
            'percent_followersCount' => '',
            'percent_interestingPage' => '',
            'percent_frequencyPost' => '',
        ];

        $percents = $this->_request->post['percent']->asArray();

        $json = json_decode(file_get_contents(ENGINE_PATH . 'engine/Service/Tasks/Model/Config.json'), true);

        foreach ($settings as $name => $val) {
            $setting = $this->factorySystem->settings->getByName($name, true);

            if ($setting === null) {
                $setting = $this->factorySystem->settings->getNewItem();
            }
            $setting->name = $name;
            $setting->value = $this->_request->post[$name]->string();
            $this->factorySystem->settings->save($setting);
        }

        foreach ($percents as $name => $vals) {
            foreach ($vals as $id => $val) {
                $json[$name][$id] = $val;
            }
        }

        file_put_contents(ENGINE_PATH . 'engine/Service/Tasks/Model/Config.json',
            json_encode($json, JSON_UNESCAPED_UNICODE));

        return null;
    }
}
