<?php

namespace Service\Users;

class Controller_State_Admin_Referrers_Settings extends Controller_State_Admin
{
    public function actionPrepare()
    {
        if (isset($this->_application->menu['users']['menu']['referrers'])) {
            $this->_application->menu['users']['menu']['referrers']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        $settings = json_decode(file_get_contents(Model_Config::$referrersPath), true);

        $vars = [
            'settings' => $settings,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/referrers/settings', $vars));
    }

    public function actionPost()
    {
        $settings = json_decode(file_get_contents(Model_Config::$referrersPath), true);
        $sets = $this->_request->post->asArray();
        $settings['percent'] = $sets;
        file_put_contents(Model_Config::$referrersPath, json_encode($settings, JSON_UNESCAPED_UNICODE));
    }
}
