<?php

namespace Service\Tasks;

/**
 * Class Controller_State_Amin
 *
 * @package Service\Tasks
 */
abstract class Controller_State_Admin extends \System\Service_Controller_State
{
    protected $_limit = 50;

    protected $_types = [
        'likes' => 'Поставить лайк',
        'reposts' => 'Сделать репост',
        'comments' => 'Оставить комментарий',
        'join' => 'Подписаться',
        'friends' => 'Добавить в друзья',
        'polls' => 'Участвовать в опросе',
        'views' => 'Просмотреть запись',
        'video' => 'Просмотреть видео',
    ];

    protected $_vkTypes = [
        'post' => 'Запись на стене',
        'photo' => 'Фотография',
        'video' => 'Видеозапись',
        'comment' => 'Комментарий',
    ];

    public function actionPrepare()
    {
        if (isset($this->_application->menu['tasks'])) {
            $this->_application->menu['tasks']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }
}
