<?php

namespace Service\Pages;

class Controller_Admin_Prices_Edit extends Controller_Admin
{
    public function actionPrepare()
    {
        $this->_price = $this->factory->prices->GetPrice(intval($this->_params['PriceID']), true);

        $this->_application->Title->addScripts(
            [
                '/js/jquery/tinymce/tinymce.min.js',
                '/js/plupload/plupload.full.min.js',
                '/js/plupload/uploader.js',
                '/js/bootstrap/bootstrap-datepicker.js',
            ]
        );

        $this->_application->Title->addStyles([
            '/js/jquery/tinymce/plugins/moxiemanager/skins/lightgray/skin.min.css',
            '/css/uploader.css',
            '/css/datepicker.css',
        ]);

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        $vars = [
            'price' => $this->_price,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/prices/edit', $vars));
    }

    public function actionPost()
    {
        $action = $this->_request->post['action']->string();

        switch ($action) {
            case 'save':
                return $this->_save();
        }

        return parent::actionPost(); // TODO: Change the autogenerated stub
    }
}
