<?php

namespace Service\Pages;

class Controller_Admin_Prices_Fields extends Controller_Admin
{
    protected $_success = false;

    public function actionPrepare()
    {
        $this->_price = $this->factory->prices->GetPrice(intval($this->_params['PriceID']), true);

        $this->_application->Title->addScripts(
            [
                '/js/jquery/tinymce/tinymce.min.js',
                '/js/plupload/plupload.full.min.js',
                '/js/plupload/uploader.js',
                '/js/bootstrap/bootstrap-datepicker.js',
            ]
        );

        $this->_application->Title->addStyles([
            '/js/jquery/tinymce/plugins/moxiemanager/skins/lightgray/skin.min.css',
            '/css/uploader.css',
            '/css/datepicker.css',
        ]);

        return parent::actionPrepare();
    }

    public function actionGet()
    {
        $vars = [
            'price' => $this->_price,
            'data' => $this->_price->getFields(),
            'success' => $this->_success,
            'errors' => $this->_errors,
        ];

        if (isset($this->_params['data'])) {
            $vars['data'] = $this->_params['data'];
        }

        return $this->_response->setBody(\STPL::Fetch('admin/prices/fields', $vars));
    }

    public function actionPost()
    {
        $action = $this->_request->post['action']->string();

        switch ($action) {
            case 'fields':
                return $this->_fields();
        }

        return parent::actionPost(); // TODO: Change the autogenerated stub
    }

    private function _fields()
    {
        $fields = [];

        if (!$this->factory->fields->deleteByPriceID($this->_price->PriceID)) {
            $this->_errors[] = 'Не удалось подготовить базу';

            return false;
        }

        foreach ($_POST['Column'] as $id => $Column) {
            $field = $this->factory->fields->getNew();

            $field->PriceID = $this->_price->PriceID;
            $field->Column = $this->_request->post['Column'][$id]->int(0);
            $field->Align = $this->_request->post['Align'][$id]->string('');
            $field->Title = $this->_request->post['Title'][$id]->string('');

            $fields[$id] = $field;
            $this->factory->fields->save($field);
        }

        $this->_params['data'] = $fields;
        $this->_errors[] = 'Данные сохранены';
        $this->_success = true;

        return false;
    }
}
