<?php

namespace Service\Users;

class Controller_State_Client_Referrer_Balance extends Controller_State_Client
{
    public function actionPrepare()
    {
        if (!$this->_application->UserIsAuth()) {
            return $this->_response->setLocation('/users/login');
        }

        $this->_application->userPage = 'referrer';
        $this->_application->Title->Title = 'Партнерская программа - реферальный баланс';

        $this->_application->Title->add('link', [
            'rel' => 'icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        $this->_application->Title->add('link', [
            'rel' => 'shortcut icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        $query = $this->factoryUsers->users->balance->query()->sort('dateCreate', 'DESC');
        $query->filter->fieldValue('userId', '=', $this->_application->UserID)
            ->fieldValue('isReferrer', '=', true);

        $it = $query->iterator();

        $list = [];

        foreach ($it as $balance) {
            $list[] = $balance;
        }

        $vars = [
            'list' => $list,
        ];

        $html = \STPL::Fetch('client/referrer/balance', $vars);

        return $this->_response->setBody($html);
    }

    public function actionPost()
    {
    }
}
