<?php

namespace Service\Users;

class Controller_State_Client_Referrer_Bonus extends Controller_State_Client
{
    public function actionPrepare()
    {
        if (!$this->_application->UserIsAuth()) {
            return $this->_response->setLocation('/users/login');
        }

        $this->_application->userPage = 'referrer';
        $this->_application->Title->Title = 'Партнерская программа - реферальные бонусы';

        $this->_application->Title->add('link', [
            'rel' => 'icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        $this->_application->Title->add('link', [
            'rel' => 'shortcut icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        $page = $this->_params['page'];
        $query = $this->factoryUsers->users->referrers->query()->limit($this->_limit)->offset(($page - 1) * $this->_limit)->sort('dateCreate',
            'DESC')->sqlCalcFoundRows(true);
        $query->filter->fieldValue('userId', '=', $this->_application->User->userId);
        $it = $query->iterator();
        $total = $it->getTotal();

        $pageslink = \Lib_Html::GetNavigationPagesNumber(
            $this->_limit,
            4,
            $it->getTotal(),
            $page,
            '/users/referrer/bonus/@p@',
            1
        );

        $vars = [
            'user' => $this->_application->User,
            'total' => $total,
            'list' => $it,
            'pageslink' => $pageslink,
        ];

        return $this->_response->setBody(\STPL::Fetch('client/referrer/bonus', $vars));
    }

    public function actionPost()
    {
        // TODO: Implement actionPost() method.
    }
}
