<?php

namespace Service\Users;

class Controller_State_Client_Referrer_List extends Controller_State_Client
{
    private $_fields = [
        1 => 'parentId',
        2 => 'pParentId',
    ];

    public function actionPrepare()
    {
        if (!$this->_application->UserIsAuth()) {
            return $this->_response->setLocation('/users/login');
        }

        $this->_application->userPage = 'referrer';
        $this->_application->Title->Title = 'Партнерская программа';

        if (!$this->_application->UserIsAuth()) {
            return $this->_response->setStatus(\System\HttpResponse::S4_FORBIDDEN);
        }
        $this->_application->Title->add('link', [
            'rel' => 'icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        $this->_application->Title->add('link', [
            'rel' => 'shortcut icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        if (!isset($this->_fields[$this->_params['level']])) {
            return $this->_response->setStatus(\System\HttpResponse::S4_NOT_FOUND);
        }

        $page = $this->_params['page'];

        $query = $this->factoryUsers->users->query()
            ->limit($this->_limit)
            ->offset($this->_limit * ($page - 1))
            ->sqlCalcFoundRows(true)
            ->sort('userId', 'DESC');
        $query->filter
            ->fieldValue($this->_fields[$this->_params['level']], '=', $this->_application->User->userId);

        $it = $query->iterator();

        $total = $it->getTotal();

        $pageslink = \Lib_Html::GetNavigationPagesNumber(
            $this->_limit,
            4,
            $it->getTotal(),
            $page,
            '/users/referrer/' . $this->_params['level'] . '/@p@',
            1
        );

        $list = [];

        foreach ($it as $user) {
            $list[] = $user;
        }

        $limits = [];

        foreach ($this->_fields as $level => $field) {
            $query = $this->factoryUsers->users->query()->limit(1)->sqlCalcFoundRows(true);
            $query->filter
                ->fieldValue($this->_fields[$level], '=', $this->_application->User->userId);

            $it = $query->iterator();

            $limits[$level] = $it->getTotal();
        }

        $vars = [
            'total' => $total,
            'level' => $this->_params['level'],
            'limits' => $limits,
            'list' => $list,
            'pageslink' => $pageslink,
        ];

        return $this->_response->setBody(\STPL::Fetch('client/referrer/list', $vars));
    }

    public function actionPost()
    {
        // TODO: Implement actionPost() method.
    }
}
