<?php

namespace Service\Users;

class Controller_State_Client_Referrer_Out extends Controller_State_Client
{
    public function actionPrepare()
    {
        $this->_application->userPage = 'referrer';
        $this->_application->Title->Title = 'Партнерская программа';

        $this->_application->Title->add('link', [
            'rel' => 'icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        $this->_application->Title->add('link', [
            'rel' => 'shortcut icon',
            'href' => '/img/icons/32/icon-referrer.png',
            'type' => 'image/png',
        ]);

        $this->_application->Title->addScript('/js/users/out.min.js');

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionGet()
    {
        $page = $this->_params['page'];
        $query = $this->factoryUsers->users->requests->query()->limit($this->_limit)->offset(($page - 1) * $this->_limit)->sort('dateCreate',
            'DESC')->sqlCalcFoundRows(true);
        $query->filter->fieldValue('userId', '=', $this->_application->User->userId);
        $it = $query->iterator();
        $total = $it->getTotal();

        $pageslink = \Lib_Html::GetNavigationPagesNumber(
            $this->_limit,
            4,
            $it->getTotal(),
            $page,
            '/users/referrer/out/@p@',
            1
        );

        $vars = [
            'status' => Model_Config::$requestsStatuses,
            'user' => $this->_application->User,
            'total' => $total,
            'list' => $it,
            'pageslink' => $pageslink,
        ];

        return $this->_response->setBody(\STPL::Fetch('client/referrer/out', $vars));
    }

    public function actionPost()
    {
        $action = $this->_request->post['action']->string();

        switch ($action) {
            case 'outPrepare':
                return $this->_outPrepare();
            case 'out':
                return $this->_out();
        }
    }

    protected function _outPrepare()
    {
        if (!$this->_application->User->qiwi) {
            return $this->_response->setJson([
                'success' => false,
                'errorText' => 'Перед подачей заявки необходимо указать кошелек qiwi.<a href="/users/general">Указать</a>',
            ]);
        }

        $settings = Model_Config::GetReferrersSettings();
        $fromDate = strtotime($settings['out']['from'] . '.' . date('m') . '.' . date('Y'));
        $toDate = strtotime($settings['out']['to'] . '.' . date('m') . '.' . date('Y'));

        if (date('d') > $settings['out']['from']) {
            $fromDate = strtotime('+1 MONTH', $fromDate);
            $toDate = strtotime('+1 MONTH', $toDate);
        }

        $vars = [
            'user' => $this->_application->User,
            'settings' => $settings,
            'fromDate' => $fromDate,
            'toDate' => $toDate,
        ];

        return $this->_response->setJson([
            'success' => true,
            'html' => \STPL::Fetch('client/referrer/out_form', $vars),
        ]);
    }

    protected function _out()
    {
        $settings = Model_Config::GetReferrersSettings();

        $balanceRef = $this->_request->post['balanceRef']->dec(0.0);

        if (!$balanceRef) {
            return $this->_response->setJson(['success' => false, 'errorText' => 'Укажите сумму']);
        }

        if ($balanceRef > $this->_application->User->balanceRef) {
            return $this->_response->setJson([
                'success' => false,
                'errorText' => 'Указанная сумма превышает Ваш баланс',
            ]);
        }

        if ($balanceRef < $settings['out']['min']) {
            return $this->_response->setJson([
                'success' => false,
                'errorText' => 'Минимальная сумма на вывод средств: <strong>' . $settings['out']['min'] . '</strong> рублей',
            ]);
        }

        $request = $this->factoryUsers->users->requests->getNew();
        $request->userId = $this->_application->User->userId;
        $request->dateCreate = time();
        $request->status = 0;
        $request->balanceRef = $balanceRef;
        $request->balanceFee = $balanceRef * ($settings['out']['fee'] / 100);
        $request->balanceTotal = $request->balanceRef + $request->balanceFee;

        if ($request->balanceTotal > $this->_application->User->balanceRef) {
            return $this->_response->setJson([
                'success' => false,
                'errorText' => 'Указанная сумма превышает Ваш баланс',
            ]);
        }

        if ($this->factoryUsers->users->requests->save($request)) {
            $user = $this->_application->User;
            $user->makeShadow();
            $user->balanceRef -= $request->balanceTotal;
            $this->factoryUsers->users->save($user);

            return $this->_response->setJson(['success' => true]);
        }
    }
}
