<?php

namespace Service\Orders;

abstract class Controller_State_Admin extends Controller_State
{
    /** @var Model_Orders_Packs_Pack */
    protected $_pack = null;

    public function actionPrepare()
    {
        if (isset($this->_application->menu['orders']['active'])) {
            $this->_application->menu['orders']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function actionPost()
    {
        return $this->_response->setStatus(\System\HttpResponse::S4_METHOD_NOT_ALLOWED);
    }

    protected function _edit()
    {
        $this->_pack->title = $this->_request->post['title']->string();
        $this->_pack->balance = $this->_request->post['balance']->int(0);
        $this->_pack->bonus = $this->_request->post['bonus']->int(0);
        $this->_pack->price = $this->_request->post['price']->dec(0.0);
        $this->_pack->serviceAll = $this->_request->post['serviceAll']->bool(false);
        $this->_pack->serviceCount = $this->_request->post['serviceCount']->int(0);
        $this->_pack->serviceMonth = $this->_request->post['serviceMonth']->int(0);
        $this->_pack->isReferrer = $this->_request->post['isReferrer']->bool(false);

        $this->factoryOrders->orders->packs->save($this->_pack);

        return $this->_response->setLocation('/admin/orders');
    }
}
