<?php

namespace Service\Orders;

class Controller_State_Admin_Services extends Controller_State_Admin
{
    public function actionPrepare()
    {
        $response = parent::actionPrepare(); // TODO: Change the autogenerated stub
        if ($response !== null) {
            return $response;
        }

        if (isset($this->_application->menu['orders']['menu']['stat_services'])) {
            $this->_application->menu['orders']['menu']['stat_services']['active'] = true;
        }
    }

    public function actionGet()
    {
        $auto = $this->factoryAuto->auto->groups->getCounts();
        $grabber = $this->factoryGrabber->groups->getCounts();
        $posting = $this->factoryPosting->groups->getCounts();
        $special = $this->factoryTasks->specialGroups->getCounts();

        $vars = [
            'total' => [
                'auto' => $auto,
                'grabber' => $grabber,
                'posting' => $posting,
                'special' => $special,
            ],
            'free' => [
                'auto' => $this->factoryAuto->auto->groups->getCounts(true),
                'grabber' => $this->factoryGrabber->groups->getCounts(true),
                'posting' => $this->factoryPosting->groups->getCounts(true),
                'special' => $this->factoryTasks->specialGroups->getCounts(true),
            ],
        ];

        $html = \STPL::Fetch('admin/services', $vars);

        return $this->_response->setBody($html);
    }

    public function actionPost()
    {
        return parent::actionPost();
    }
}
