<?php

namespace Service\Orders;

class Controller_State_Admin_Stat extends Controller_State_Admin
{
    public function actionPrepare()
    {
        $response = parent::actionPrepare();

        if ($response !== null) {
            return $response;
        }

        if (isset($this->_application->menu['orders']['menu']['stat'])) {
            $this->_application->menu['orders']['menu']['stat']['active'] = true;
        }

        return null;
    }

    public function actionGet()
    {
        $query = $this->factoryOrders->orders->packs->query()->limit(100)->sort('price', 'ASC');
        $it = $query->iterator();
        $list = [];

        foreach ($it as $pack) {
            $list[$pack->packId] = $pack;
        }

        $months = $this->factoryOrders->orders->getTotalsByMonths();
        $packs = $this->factoryOrders->orders->getPacksByMonths();
        $services = $this->factoryOrders->orders->getServicesByMonths();
        $balance = $this->factoryOrders->orders->getBalanceByMonths();
        $karma = $this->factoryOrders->orders->getKarmaByMonths();

        $from = $this->_request->get['dateFrom']->dateTime(strtotime('-30 DAY'));
        $to = $this->_request->get['dateTo']->dateTime(time());

        $stat = $this->factoryOrders->orders->getStatByDay($from, $to);
        $done = $this->factoryOrders->orders->getStatByDay($from, $to, true);

        $sum = $this->factoryOrders->orders->getSumByDay($from, $to);
        $sumDone = $this->factoryOrders->orders->getSumByDay($from, $to, true);

        $time = $to;
        $keys = [];

        while ($time > $from) {
            $keys[date('Y-m-d', $time)] = date('d.m.Y', $time);
            $time -= 86400;
        }

        $vars = [
            'titles' => [
                'isAuto' => 'Автоведение',
                'isPosting' => 'Автопостинг',
                'isGrabber' => 'Граббер',
                'isSpecial' => 'Спецзадания',
                'isBot' => 'Автобот',
            ],
            'list' => $list,
            'packs' => $packs,
            'services' => $services,
            'months' => $months,
            'balance' => $balance,
            'karma' => $karma,
            'from' => $from,
            'to' => $to,
            'keys' => $keys,
            'stat' => $stat,
            'done' => $done,
            'sum' => $sum,
            'sumDone' => $sumDone,
        ];

        return $this->_response->setBody(\STPL::Fetch('admin/stat', $vars));
    }

    public function actionPost()
    {
        return parent::actionPost(); // TODO: Change the autogenerated stub
    }
}
