<?php

namespace Service\Pages;

/**
 * Class Controller_Client
 *
 * @package Service\Pages
 *
 * @property Model_Pages $pages
 * @property Model_Factory $factory
 */
abstract class Controller_Admin extends \System\Service_Controller_State
{
    protected $limit = 50;
    protected $errors = false;
    /** @var Model_Pages_Page|null */
    protected $_page = null;
    /** @var Model_Prices_Price */
    protected $_price = null;
    private $_pages = null;
    private $_factory = null;

    public function actionPrepare()
    {
        if (isset($this->_application->menu['pages'])) {
            $this->_application->menu['pages']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    public function __get($name)
    {
        switch ($name) {
            case 'pages':
                if ($this->_pages === null) {
                    $this->_pages = new Model_Pages();
                }

                return $this->_pages;
            case 'factory':
                if ($this->_factory === null) {
                    $this->_factory = new Model_Factory();
                }

                return $this->_factory;
        }

        return null;
    }

    /**
     * @return \System\HttpResponse|null
     */
    public function actionPost()
    {
        $action = $this->_request->post['action']->string();

        switch ($action) {
            case 'upload':
                return $this->_upload();
            case 'delete':
                return $this->_delete();
        }

        return $this->_response->setStatus(\System\HttpResponse::S4_METHOD_NOT_ALLOWED);
    }

    private function _upload()
    {
        $uuid = $this->_request->post['uuid']->string();

        $dir = [
            'big' => IMAGES_PATH . 'temp/big/' . $uuid,
            'small' => IMAGES_PATH . 'temp/small/' . $uuid,
        ];

        if (!is_dir($dir['big'])) {
            mkdir($dir['big'], 0777, true);
        }

        if (!is_dir($dir['small'])) {
            mkdir($dir['small'], 0777, true);
        }

        if (!is_file($_FILES['file']['tmp_name'])) {
            return $this->_response->setJson(['error' => 'FUCK!!!']);
        }

        $info = @getimagesize($_FILES['file']['tmp_name']);

        if ($info === false) {
            $err = error_get_last();

            return $this->_response->setJson(['error' => $err['message']]);
        }

        if (($res = \Lib_Images::PrepareResize($_FILES['file']['tmp_name'], 0, 200, 130))) {
            \Lib_Images::Resize($_FILES['file']['tmp_name'], $dir['small'] . '/' . $_FILES['file']['name'], $res);
        }

        if (($res = \Lib_Images::PrepareResize($_FILES['file']['tmp_name'], 0, 600, 600))) {
            \Lib_Images::Resize($_FILES['file']['tmp_name'], $dir['big'] . '/' . $_FILES['file']['name'], $res);
        }

        $result = [
            'success' => true,
            'jsonrpc' => '2.0',
            'key' => \Lib_Uuid::getNext(),
            'name' => $_FILES['file']['name'],
            'url' => '/images/temp/big/' . $uuid . '/' . $_FILES['file']['name'],
            'url_preview' => '/images/temp/small/' . $uuid . '/' . $_FILES['file']['name'],
        ];

        return $this->_response->setJson($result);
    }

    private function _delete()
    {
        $uuid = $this->_request->post['uuid']->string();
        $name = $this->_request->post['key']->string();

        $dirs = [
            IMAGES_PATH . 'temp/big/' . $uuid . '/',
            IMAGES_PATH . 'temp/small/' . $uuid . '/',
            IMAGES_PATH . 'articles/big/',
            IMAGES_PATH . 'articles/small/',
        ];

        foreach ($dirs as $dir) {
            if (is_file($dir . $name)) {
                @unlink($dir . $name);
            }
        }

        $this->_page->makeShadow();

        if ($name == $this->_page->photo) {
            $this->_page->photo = '';
            $this->pages->save($this->_page);
        }

        return $this->_response->setJson(['success' => true]);
    }

    public function _save()
    {
        $this->_price->Title = $this->_request->post['Title']->string();
        $this->_price->TitleMain = $this->_request->post['TitleMain']->string();
        $this->_price->Description = $this->_request->post['Description']->string();
        $this->_price->Date = $this->_request->post['Date']->dateTime();
        $this->_price->Order = $this->_request->post['Order']->int(0);
        $this->_price->Text = $this->_request->post['Text']->string();

        $this->factory->prices->save($this->_price);

        return $this->_response->setLocation('/admin/pages/prices');
    }

    protected function _edit($client = false, $url = '')
    {
        $this->_page->title = $this->_request->post['title']->string();
        $this->_page->describe = $this->_request->post['describe']->string();
        $this->_page->keywords = $this->_request->post['keywords']->string();
        $this->_page->text = $this->_request->post['text']->string();

        if (!$this->_page->strict) {
            $this->_page->alias = $this->_request->post['alias']->string();
        }

        if (!$this->_page->alias) {
            $this->_page->alias = \Lib_Text::Translit($this->_page->title);
        }

        if (!$this->_page->dateCreate) {
            $this->_page->dateCreate = time();
        }
        $this->_page->lastDate = time();

        if ($client === true) {
            $this->_page->userId = $this->_application->UserID;
        }
        $this->_page->lastUserId = $this->_application->UserID;

        $this->_page->announce = $this->_request->post['announce']->bool();

        $this->_errors = $this->_page->check();

        if ($this->_errors !== false) {
            return false;
        }

        $this->_page->photo = $this->uploadPhoto();

        if (!$this->pages->save($this->_page)) {
            $this->errors[] = 'Не удалось сохранить страницу';

            return false;
        }

        if ($this->_page->isArticle) {
            return $this->_response->setLocation('/admin/pages/articles/1');
        } elseif ($this->_page->isNew) {
            if ($url) {
                return $this->_response->setLocation($url);
            }

            return $this->_response->setLocation('/admin/pages/news/1');
        }

        return $this->_response->setLocation('/admin/pages/list/1');
    }

    protected function uploadPhoto()
    {
        $uuid = $this->_request->post['uuid']->string();

        $dir = [
            'big' => IMAGES_PATH . 'temp/big/' . $uuid,
            'small' => IMAGES_PATH . 'temp/small/' . $uuid,
        ];

        $photo = $this->_page->photo;

        if (is_dir($dir['big'])) {
            $dirs = new \DirectoryIterator($dir['big']);

            foreach ($dirs as $file) {
                if (!is_file($dir['small'] . '/' . $file)) {
                    continue;
                }

                $path = rand(10, 99) . '/' . rand(10, 99) . '/' . rand(10, 99);

                if (!is_dir(IMAGES_PATH . 'articles/big/' . $path)) {
                    mkdir(IMAGES_PATH . 'articles/big/' . $path, 0777, true);
                }

                if (!is_dir(IMAGES_PATH . 'articles/small/' . $path)) {
                    mkdir(IMAGES_PATH . 'articles/small/' . $path, 0777, true);
                }

                $photo = $path . '/' . $file;

                rename($dir['big'] . '/' . $file, IMAGES_PATH . 'articles/big/' . $photo);
                rename($dir['small'] . '/' . $file, IMAGES_PATH . 'articles/small/' . $photo);

                break;
            }

            foreach ($dir as $path) {
                rmdir($path);
            }
        }

        return $photo;
    }
}
