<?php

namespace Service\News;

use DirectoryIterator;
use Lib_Images;
use Lib_Text;
use Lib_Uuid;
use System\HttpResponse;
use System\Service_Controller_State;

/**
 * Class Controller_State_Admin
 *
 * @package Service\News
 */
abstract class Controller_State_Admin extends Service_Controller_State
{
    protected $limit = 50;

    protected $errors = false;

    /** @var Model_News_New|null */
    protected $_new = null;

    public function actionPrepare()
    {
        if (isset($this->_application->menu['news'])) {
            $this->_application->menu['news']['active'] = true;
        }

        return parent::actionPrepare(); // TODO: Change the autogenerated stub
    }

    /**
     * @return HttpResponse|null
     */
    public function actionPost()
    {
        $action = $this->_request->post['action']->string();

        switch ($action) {
            case 'upload':
                return $this->_upload();
            case 'delete':
                return $this->_delete();
        }

        return $this->_response->setStatus(HttpResponse::S4_METHOD_NOT_ALLOWED);
    }

    private function _upload()
    {
        $uuid = $this->_request->post['uuid']->string();

        $dir = [
            'big' => IMAGES_PATH . 'temp/big/' . $uuid,
            'small' => IMAGES_PATH . 'temp/small/' . $uuid,
        ];

        if (!is_dir($dir['big'])) {
            mkdir($dir['big'], 0777, true);
        }

        if (!is_dir($dir['small'])) {
            mkdir($dir['small'], 0777, true);
        }

        if (!is_file($_FILES['file']['tmp_name'])) {
            return $this->_response->setJson(['error' => 'FUCK!!!']);
        }

        $info = @getimagesize($_FILES['file']['tmp_name']);

        if ($info === false) {
            $err = error_get_last();

            return $this->_response->setJson(['error' => $err['message']]);
        }

        if (($res = Lib_Images::PrepareResize($_FILES['file']['tmp_name'], 0, 200, 130))) {
            Lib_Images::Resize($_FILES['file']['tmp_name'], $dir['small'] . '/' . $_FILES['file']['name'], $res);
        }

        if (($res = Lib_Images::PrepareResize($_FILES['file']['tmp_name'], 0, 600, 600))) {
            Lib_Images::Resize($_FILES['file']['tmp_name'], $dir['big'] . '/' . $_FILES['file']['name'], $res);
        }

        $result = [
            'success' => true,
            'jsonrpc' => '2.0',
            'key' => Lib_Uuid::getNext(),
            'name' => $_FILES['file']['name'],
            'url' => '/img/temp/big/' . $uuid . '/' . $_FILES['file']['name'],
            'url_preview' => '/img/temp/small/' . $uuid . '/' . $_FILES['file']['name'],
        ];

        return $this->_response->setJson($result);
    }

    private function _delete()
    {
        $uuid = $this->_request->post['uuid']->string();
        $name = $this->_request->post['key']->string();

        $dirs = [
            IMAGES_PATH . 'temp/big/' . $uuid . '/',
            IMAGES_PATH . 'temp/small/' . $uuid . '/',
            IMAGES_PATH . 'news/big/',
            IMAGES_PATH . 'news/small/',
        ];

        foreach ($dirs as $dir) {
            if (is_file($dir . $name)) {
                @unlink($dir . $name);
            }
        }

        $this->_new->makeShadow();
        $photo = $this->_new->getPhoto();

        if ($name == $photo['small']['path']) {
            $this->_new->setPhoto([]);
            $this->factoryNews->save($this->_new);
        }

        return $this->_response->setJson(['success' => true]);
    }

    /**
     * @return HttpResponse|null
     */
    protected function _edit()
    {
        $this->_new->title = $this->_request->post['title']->string();
        $this->_new->desc = $this->_request->post['describe']->string();
        $this->_new->keywords = $this->_request->post['keywords']->string();
        $this->_new->text = $this->_request->post['text']->string();

        if (!$this->_new->alias) {
            $this->_new->alias = Lib_Text::Translit($this->_new->title);
        }

        if (!$this->_new->dateCreate) {
            $this->_new->dateCreate = time();
        }
        $this->_new->dateUpdate = time();
        $this->_new->userId = $this->_application->UserID;

        $this->_new->announce = $this->_request->post['announce']->bool();

        if (!$this->_new->title) {
            $this->errors[] = 'Необходимо указать заголовок';
        }

        if (!$this->_new->desc) {
            $this->errors[] = 'Необходимо указать краткое описание';
        }

        if (!$this->_new->keywords) {
            $this->errors[] = 'Необходимо указать ключевые слова';
        }

        if (!$this->_new->text) {
            $this->errors[] = 'Необходимо указать текст новости';
        }

        if (count($this->_errors)) {
            return null;
        }

        $this->_new->setPhoto($this->uploadPhoto());

        $testNew = $this->factoryNews->news->getByAlias($this->_new->alias);

        if ($testNew !== null && $testNew->newId != $this->_new->newId) {
            $this->_errors[] = 'Новость с таким заголовком уже есть. Укажите новый';

            return null;
        }

        if (!$this->factoryNews->news->save($this->_new)) {
            $this->errors[] = 'Не удалось сохранить новость';

            return null;
        }

        return $this->_response->setLocation('/admin/news/list/1');
    }

    protected function uploadPhoto()
    {
        $uuid = $this->_request->post['uuid']->string();

        $dir = [
            'big' => IMAGES_PATH . 'temp/big/' . $uuid,
            'small' => IMAGES_PATH . 'temp/small/' . $uuid,
        ];

        $photo = $this->_new->getPhoto();

        if (is_dir($dir['big'])) {
            $dirs = new DirectoryIterator($dir['big']);

            foreach ($dirs as $file) {
                if (!is_file($dir['small'] . '/' . $file)) {
                    continue;
                }

                $path = rand(10, 99) . '/' . rand(10, 99) . '/' . rand(10, 99);

                if (!is_dir(IMAGES_PATH . 'news/big/' . $path)) {
                    mkdir(IMAGES_PATH . 'news/big/' . $path, 0777, true);
                }

                if (!is_dir(IMAGES_PATH . 'news/small/' . $path)) {
                    mkdir(IMAGES_PATH . 'news/small/' . $path, 0777, true);
                }

                $photo = [
                    'small' => [
                        'path' => $path . '/' . $file,
                        'url' => '/img/news/small/' . $path . '/' . $file,
                    ],
                    'big' => [
                        'path' => $path . '/' . $file,
                        'url' => '/img/news/big/' . $path . '/' . $file,
                    ],
                ];

                rename($dir['big'] . '/' . $file, IMAGES_PATH . 'news/big/' . $photo['big']['path']);
                rename($dir['small'] . '/' . $file, IMAGES_PATH . 'news/small/' . $photo['small']['path']);

                break;
            }

            foreach ($dir as $path) {
                rmdir($path);
            }
        }

        return $photo;
    }
}
